StatViewer = {}
TESOStat={STAT_ARMOR_RATING,
STAT_ATTACK_POWER,
STAT_BLOCK,
STAT_CRITICAL_RESISTANCE,
STAT_CRITICAL_STRIKE,
STAT_DAMAGE_RESIST_COLD,
STAT_DAMAGE_RESIST_DISEASE,
STAT_DAMAGE_RESIST_DROWN,
STAT_DAMAGE_RESIST_EARTH,
STAT_DAMAGE_RESIST_FIRE,
STAT_DAMAGE_RESIST_GENERIC,
STAT_DAMAGE_RESIST_MAGIC,
STAT_DAMAGE_RESIST_OBLIVION,
STAT_DAMAGE_RESIST_PHYSICAL,
STAT_DAMAGE_RESIST_POISON,
STAT_DAMAGE_RESIST_SHOCK,
STAT_DAMAGE_RESIST_START,
STAT_DODGE,
STAT_HEALTH_MAX,
STAT_HEALTH_REGEN_COMBAT,
STAT_HEALTH_REGEN_IDLE,
STAT_MAGICKA_MAX,
STAT_MAGICKA_REGEN_COMBAT,
STAT_MAGICKA_REGEN_IDLE,
STAT_MISS,
STAT_MITIGATION,
STAT_PHYSICAL_PENETRATION,
STAT_PHYSICAL_RESIST,
STAT_POWER,
STAT_SPELL_CRITICAL,
STAT_SPELL_MITIGATION,
STAT_SPELL_PENETRATION,
STAT_SPELL_POWER,
STAT_SPELL_RESIST,
STAT_STAMINA_MAX,
STAT_STAMINA_REGEN_COMBAT,
STAT_STAMINA_REGEN_IDLE,
STAT_WEAPON_AND_SPELL_DAMAGE="STAT_WEAPON_AND_SPELL_DAMAGE"}

StatViewer.name="StatViewer"
StatViewer.maxHealth=""
StatViewer.textMaxHealth="Max Health : "
StatViewer.maxMagicka=""
StatViewer.textMaxMagicka="Max Magicka : "
StatViewer.maxStam=""
StatViewer.textMaxStam="Max Stamina : "

function StatViewer:Initiliaze()
  EVENT_MANAGER:RegisterForEvent(StatViewer.name, EVENT_STATS_UPDATED, StatViewer.UpdateStats)
  
end

function StatViewer.OnAddOnLoaded(event, addonName)
  if addonName==StatViewer.name then
    StatViewer.Initiliaze()
  end
end

function StatViewer.UpdateStats(event)
for x,t in pairs(TESOStat) do
SVIndicatorLabel:SetText(t.." : "..GetPlayerStat(x,STAT_BONUS_OPTION_APPLY_BONUS))
end
end

EVENT_MANAGER:RegisterForEvent(StatViewer.name, EVENT_ADD_ON_LOADED, StatViewer.OnAddOnLoaded)